### ISSUE TITLE
Less compilation breaks on files that only contain comments

### ISSUE THREAD

**Issue by dcryan** [plus3network/gulp-less#114]
This wasn't an issue with 1.3.6

Breaks when trying to compile files that only contain comments both single line and multi-line

Example 1:
```
// breaks on single line comments
```

Example 2:
```
/*
breaks also on multi-line comments
with a following commented less example
div{
background: transparent;
}
*/
```

**Comment by contra** [comment]
This is a duplicate of https://github.com/less/less.js/issues/2430
