### ISSUE TITLE
Less compilation doesn't break on missing variable

### ISSUE THREAD

**Issue by mike-engel** [plus3network/gulp-less#118]
Not sure if this issue should be here or in the less repo, but here it is. I recently did a lot of refactoring and after deleting a certain file, the less task would never finish, which would cause more problems in the default task as you can imagine. After going through all the changes, I found that I had deleted a variable that was used in another file. Even though less should have thrown an error about a missing variable, it didn't.

I'm not sure if I've missed something with less 2.0.0 or if this is a bug between one or both repos.

Thanks!

**Comment by magicdawn** [comment]
I don't understand what's doing in the index.js

```js
cb(error)
```
since we can't see the error. why not just use `gutil.log` tell us what's wrong...

**Comment by magicdawn** [comment]
here is the  problem :  plugin catch error & pass to the callback & no error show on console

**Comment by contra** [comment]
I have a test case that is reproducing this but I have no idea why the error isn't ending the stream

**Comment by contra** [comment]
fixed in 2.0.3

**Comment by austinpray** [comment]
@retlehs

**Comment by mike-engel** [comment]
Many thanks @contra and @OhJeez.

**Comment by umefarooq** [comment]
thanks for fixing
