### ISSUE TITLE
using Less Autoprefix plugin breaks sourcemaps (sources property)

### ISSUE THREAD

**Issue by bassjobsen** [plus3network/gulp-less#126]
When i using the following gulpfile.js:
```javascript
var gulp = require('gulp'),
    less = require('gulp-less'),
    sourcemaps = require('gulp-sourcemaps');

var LessPluginAutoPrefix = require('less-plugin-autoprefix'),
    autoprefix= new LessPluginAutoPrefix({browsers: ["last 2 versions"]});

gulp.task('default', function () {
  return gulp
 .src('./less/**/*.less')
 .pipe(sourcemaps.init())
  .pipe(less({
    plugins: [autoprefixer]
   }))
  .pipe(sourcemaps.write('./'))
  .pipe(gulp.dest('./css'));
});
```

The source map got a invalid second value for the sources property (`"../<input css 1>"`).

The sourcemap code looks like that shown below:

```json
{"version":3,"sources":["t.less","../<input css 1>"],"names":[],"mappings":
```
When using `autoprefixer = require('gulp-autoprefixer');` with `.pipe(autoprefixer())` instead of the plugin, the generated sourcemap is correct.

To verify if the problem is not related to the Less Autoprefix plugin itself, i have compiled the Less code with the command line Less compiler and the autoprefix plugin by running: `lessc less/t.less css/t.css --autoprefix --source-map --source-map-less-inline`. Also the preceding command gives an sourcemap as expected (`{"version":3,"sources":["../less/t.less","t.css"],"names":[]`)

**Comment by contra** [comment]
No idea - less should be dealing with the sourcemaps of plugins before it even hands data back to us. Will take some debugging.

**Comment by bassjobsen** [comment]
I understand now your are using inline sourcemap. So i tested `lessc less/t.less  --autoprefix --source-map --source-map-less-inline --source-map-map-inline` which generates a wrong sourcemap. So the issue is related to the Less plugin (or Less) indeed.

**Comment by contra** [comment]
Reopen on the relevant repo and link to this issue so people can track the progress

**Comment by bassjobsen** [comment]
Even when https://github.com/postcss/autoprefixer-core/issues/27 is a bug and you have to set the sourceMapFileInline option indeed. It seems to make sense to set result.map.file = file.relative; before:

```javascript
     for (var i = 0; i < sourceMap.sources.length; i++) {
                sourceMap.sources[i] = path.relative(file.base, sourceMap.sources[i]);
              }
```

Because of gulp-sourcemaps uses the `file` property to set a value in the `sources` property.
