### ISSUE TITLE
invalid sourcemap comment is removed

### ISSUE THREAD

**Issue by boogerlad** [plus3network/gulp-less#130]
Hi, I'm using `gulp-less` and `bower-files`. Just as an experiement, I've passed in bootstrap's bootstrap.css to `gulp-less` and noticed that it removed the sourcemap comment at the bottom of the file! Invoking `lessc` from the command line doesn't do that. It's not a huge problem for me, but I'm wondering why it does that? Is it because the .map file isn't in the "main" files in bower.json and thus the plugin can't see it, marks it as invalid, and then removes it? Can someone point me to where in the code it does this?

**Comment by contra** [comment]
Put `loadMaps: true` into your sourcemaps.init call

**Comment by boogerlad** [comment]
I forgot to mention that I'm not using sourcemaps in my gulpfile at all. There are no calls to `sourcemaps.init()` or `sourcemaps.write()`. I'm just wondering why the default comment at the bottom of `bootstrap.css` gets removed if passed through this.

**Comment by contra** [comment]
Hmm that is weird, probably something to do with the difference between what less exposed on the command line and what it exposes programmatically

**Comment by boogerlad** [comment]
Okay I will try to reproduce this programmatically.

**Comment by contra** [comment]
@boogerlad Opened an issue for you ^

**Comment by boogerlad** [comment]
I've wasted my sanity and it appears that this has been fixed recently. Haven't `npm update`d for a week but doing so now seems to have fixed it.
