### ISSUE TITLE
Failing test and now not working?

### ISSUE THREAD

**Issue by Amparose** [plus3network/gulp-less#133]
After updating npm packages my project now doesn't seem to compile LESS. There is no error msg just `Starting 'less'...` and then process quits. No CSS is output.

I'm not sure how to roll back to a version that works so will there be a fix soon?

**Comment by stevelacy** [comment]
[1.3.8](https://github.com/plus3network/gulp-less/releases/tag/v1.3.8) is the last version before switching to less 2.0.

**Comment by Amparose** [comment]
Hmm so when will this be fixed?

**Comment by istinspring** [comment]
Huh, i thought i did something wrong. Same, fails just silently.

**Comment by contra** [comment]
Fixed in 2.0.3
