### ISSUE TITLE
couldn't add less plugins

### ISSUE THREAD

**Issue by Tommassissimo** [plus3network/gulp-less#134]
I try to enable cleancss & autoprefixer plugins in gulp-less task.
But when I run the gulp command, it shows the following errors:
![image](https://cloud.githubusercontent.com/assets/1832223/6092615/9c8ae4f6-af21-11e4-8310-20bab5d26951.png)

My gulpfile is written as following:
var gulp = require('gulp');
var less = require('gulp-less');
var LessPluginAutoPrefix = require('less-plugin-autoprefix');
var autoprefix= new LessPluginAutoPrefix({browsers: ["last 2 versions"]});
var LessPluginCleanCSS = require("less-plugin-clean-css");
var cleancss = new LessPluginCleanCSS({advanced: true});
gulp.task('less',function(){
  return gulp.src('./less/test.less')
    .pipe(less({
      plugins: [cleancss,autoprefix]
    }))
    .pipe(gulp.dest('./public/css'));
});
gulp.task('default',['less']);

test.less is a simple test file contains  'a{display:box};'

And the dependency version is as following:
  "devDependencies": {
    "gulp": "^3.8.10",
    "gulp-less": "^1.3.9",
    "less-plugin-autoprefix": "^1.3.0",
    "less-plugin-clean-css": "^1.5.0"
  }

**Comment by stevelacy** [comment]
Please create a test repo to reproduce the error.

**Comment by Tommassissimo** [comment]
thanks for your suggestion, I updated the gulp-less version to 2.0.1 and it works now.
