### ISSUE TITLE
Plugin Error - Error Handling

### ISSUE THREAD

**Issue by mikejr83** [plus3network/gulp-less#137]
I've had a head scratcher of a time trying to figure out why my gulp build was failing.

I was able to narrow down the issue to my *less* task failing. I took a look at my code and saw there had been a number of changes to our less files, but I was getting no compilation errors, or so it seemed.

After dropping a *console.log* into the error case of your stream handler I saw that it was preparing the PluginError object and calling the callback function with that object. In other words, the gulp-less plugin is seeing an error from the less module and handling it appropriately, as it should. 

The problem is that I'm not seeing any error. My task is very similar to your example:

    gulp.task('less', function () {
      return gulp.src(['./less/**/*.less', '!./less/variables.less'])
        .pipe($.sourcemaps.init())
        .pipe($.less())
        .pipe($.sourcemaps.write())
        .pipe(gulp.dest('.tmp/styles'));
    });

How can I get the PluginError object to be bubbled up to the console?

**Comment by oliversong** [comment]
I'm also seeing this in 2.0.1, not sure how to proceed aside from just downgrading.

**Comment by stevelacy** [comment]
`gulp-less` returns the error received from less to the stream. If you are using a loader it may affect the outputted error. 
The change from `gulp-less`@1.x to 2.x is a switch from `less`@1.x to 2.x.
Please create a repo to reproduce the error.

**Comment by mattstyles** [comment]
Have you tried plugging in plumber?

**Comment by mikejr83** [comment]
@stevelacy, this may be a more general question than an "issue". I honestly didn't know how to open a dialogue with you/gulp-less on how to handle LESS parser errors during the gulp build other than creating an "issue" on the repo.

So since gulp-less is returning the error to the stream I should just us a `on('error', function)` handler to catch this?

**Comment by mikejr83** [comment]
Ok. After trying my previous comment it seems like this is the acceptable way to handle the errors generated by a plugin during the gulp task. I was assuming there was some other error handling method, but if using `on('error', function)` is OK then I'm find doing this.

**Comment by stevelacy** [comment]
Ah, yes. The error is a regular js stream event.
