### ISSUE TITLE
Problem with sourcemap generation

### ISSUE THREAD

**Issue by nshulipa** [plus3network/gulp-less#145]
When trying to do this

    var autoprefix= new LessPluginAutoPrefix();
    var lessConfig = {
        paths: [ path.join(__dirname, 'less', 'includes') ],
        plugins: [autoprefix]
    };

    gulp.src(getStylesSource())
            .pipe(sourcemaps.init())
            .pipe(gulpif(/[.]less$/, less(lessConfig)))
            .pipe(sourcemaps.write())

I get this

    Potentially unhandled rejection [2] Error: ENOENT, open '<input css 1>'
        at Error (native)

but compiled css is ok, only see thir annoying warning

But when I do this

    var autoprefix= new LessPluginAutoPrefix();
    var lessConfig = {
        paths: [ path.join(__dirname, 'less', 'includes') ],
       plugins: [autoprefix]
    };

    gulp.src(getStylesSource())
            //.pipe(sourcemaps.init())
            .pipe(gulpif(/[.]less$/, less(lessConfig)))
            //.pipe(sourcemaps.write())

all is fine

versions:

     node v0.12.0
     npm v2.5.1

    "gulp-less": "^3.0.0",
    "gulp-sourcemaps": "^1.3.0"

Could you, please, explain, what I'm doing wrong?

**Comment by contra** [comment]
Can you provide a repo that reproduces the issue?

**Comment by stebru** [comment]
Was getting the same error. Seems to be caused by https://github.com/less/less-plugin-autoprefix. I set up a repo that reproduces the issue here: https://github.com/stebru/gulp-less-test

**Comment by contra** [comment]
Use gulp-autoprefixer if the less plugin isnt working, most plugins for less and stylus don't support sourcemaps very well
