### ISSUE TITLE
relative urls

### ISSUE THREAD

**Issue by achtan** [plus3network/gulp-less#149]
Hi, 

how can i setup gulp-less to use relative urls like `lessc --relative-urls ` ?

**Comment by contra** [comment]
https://github.com/plus3network/gulp-less/blob/master/README.md#options

which links to http://lesscss.org/#using-less-configuration

which says nothing about it. You should open an issue on less and ask what the option is for this

**Comment by achtan** [comment]
but in http://lesscss.org/#client-side-usage-browser-options you can see `relativeUrls: false,` so if its possible in browser its should be possible on server as well
+ grunt less also support relative-urls https://github.com/gruntjs/grunt-contrib-less#relativeurls

**Comment by contra** [comment]
@achtan We pass the options straight through to less.render so if it isn't working it is a less bug plain and simple.

**Comment by achtan** [comment]
its working!
```
.pipe(less({
        relativeUrls: true
    }))
```

**Comment by smithag77** [comment]
@achtan you are my hero.  Been cursing about this for hours now.
