### ISSUE TITLE
Usage with gulp.watch broken: if an error occurs less is not run on subsequent saves.

### ISSUE THREAD

**Issue by austinpray** [plus3network/gulp-less#152]
Here is a reduced testcase: https://gist.github.com/austinpray/dd63f2f79e23cf3317e7

### Expected behavior: 

As a user running `gulp watch`

1. save file with error 
2. less fails to compile and error prints to console
3. save file again with error removed
4. less compiles

### Behavior I am getting:

1. save file with error 
2. less fails to compile and error prints to console
3. save file again with error removed
4. nothing happens

**Comment by stevelacy** [comment]
This is the correct and expected behavior of gulp and gulp plugins.

**Comment by austinpray** [comment]
It definitely should not be silently failing to recompile on subsequent saves. 

If I had to name names: gulp-sass, gulp-ruby-sass, gulp-jshint work the way I am expecting.

**Comment by contra** [comment]
this is a gulp issue not a gulp-less issue, there are already items open for this over there. it will be fixed in gulp 4

**Comment by austinpray** [comment]
I would appreciate you guys taking a closer look at this.

>no, none of those other plugins work the way you are saying.

They really do. They are all compatible with gulp-watch one way or another. 

- [Jshint will not fail a watch](https://github.com/spalger/gulp-jshint/blob/33e08e7ce07003c1bd3090e4d80fce0b849cfe44/README.md#fail-reporter)
- [gulp-sass allows one to log errors to console rather than fail the watch task](https://github.com/dlmanning/gulp-sass/blob/ec61ffbdde111bf2fc06320aa35a703c64a47248/index.js#L66)
- [In gulp-ruby-sass you can "handle Sass errors with an on('error', cb) listener or a plugin like plumber."](https://github.com/sindresorhus/gulp-ruby-sass/blob/15e806bbd920b33ccb09cb70eb9d6df9b43c78ee/readme.md#usage)

The point being: you can put any of these plugins in your watch task and you will not have to rerun your watch task if there is an error. The gulp-sass solution seems pretty straightforward, would you consider a PR with similar functionality to hold down the fort until gulp4 comes out?

**Comment by contra** [comment]
@austinpray Those are non standard ways of handling errors that circumvent node's way of doing it. That isn't how plugins are supposed to deal with this - they shouldn't deal with it at all. It is up to the user to handle their errors, and up to us to not have gulp.watch fail. If you want a temporary fix use gulp-plumber to deal with the error management

**Comment by austinpray** [comment]
@contra fair enough. The plumber solution was initially causing undefined behavior in my gulpfile but [working in a reduced testcase](https://gist.github.com/austinpray/bbc4886ef950d6abd1e9). After some finagling got it working the way I like it. Excited for gulp4!

**Comment by braco** [comment]
@austinpray how did you fix this?

**Comment by karlhorky** [comment]
@austinpray I would like to know as well

**Comment by austinpray** [comment]
@braco @karlhorky I added a `this.emit('end')` to the error handler. 

https://github.com/roots/sage/blob/9ee41494f7f0c0102e9e42bcc581c31ba9e117b0/gulpfile.js#L149

**Comment by karlhorky** [comment]
Thanks @austinpray! With the `this.emit('end')` that works.
