### ISSUE TITLE
Compilation fails with single line comments

### ISSUE THREAD

**Issue by adam-beck** [plus3network/gulp-less#153]
I have a very simple rule in my `main.less`:

```
body {
  color: green;
// color: red;
}
```

When I try compiling with `gulp-less` I get the following error:
```
CssSyntaxError: /repos/proj/styles/index.less:3:5: Unknown word 
    color: green;
//    color: red;
      ^
}
```

This is not an issue of the `//` being the first 2 characters of the line. It works fine if I remove the commented line. And it also **works** if I use multi-line comments:

```
body {
  color: green;
  /*  color: red; */
```

I don't think this is necessarily related to #114 since the file is not empty and contains more than just variables. 

I tested this using the `lessc` CLI and it properly removes the commented line. So, I don't think this is particularly a `less` issue.

**Comment by contra** [comment]
Please compare the version of less gulp-less uses to the version of lessc you used and make sure they are the same. If not, please update lessc or downgrade or whatever you need to do to make them the same and test again.

**Comment by adam-beck** [comment]
I feel like an idiot. This issue doesn't seem to be related to `gulp-less`. I didn't isolate the problem and had another task running after `less()`.
