### ISSUE TITLE
Gulp less fails only when using gulp.watch.

### ISSUE THREAD

**Issue by digitalmaster** [plus3network/gulp-less#155]
I have a really weird issue going on here where if i run `gulp less` everything works as expected, no errors and assets are created perfectly. However, if i start the watch task and make ANY change the output is empty. Any idea why this is happening?

Less Task:

        gulp.task('less', function(){
            return gulp.src('./htdocs/css/main.less')
                .pipe(plugins.less({compress: false}))
                .pipe(gulp.dest('./htdocs/packed/'))
        });

Watch Task:

        gulp.task('default', ['less'], function(){
            gulp.watch('./htdocs/css/**/*.less', ['less']);
        });

I've spend all day yesterday trying to figure this out.

**Comment by digitalmaster** [comment]
So the culprit is a race condition in gulp.watch.. or more specifically Gaze! 

It's not waiting for the file to finish writing before firing the change event so when gulp-less runs it's doing so on a partial file. I've found a temporary solution that works for now which solved the problem by basically wrapping a setTimout function around the less code! #ugly #butWorks

        gulp.task('less', function(){
            setTimeout(function(){
                return gulp.src('./htdocs/css/main.less')
                    .pipe(plugins.plumber({
                        errorHandler: onError
                    }))
                    .pipe(plugins.less({compress: false}))
                    .pipe(plugins.autoprefixer('last 2 version', 'ie 8', 'ie 9'))
                    .pipe(gulp.dest('./htdocs/packed/'))
                    .pipe(reload({stream:true}));
            }, 300)
        });

I'm hoping there's a better way to solve this issue. If there is please let me know.

**Comment by contra** [comment]
there is a delay option for gaze. we are possibly getting rid of gaze due to bugs like this. adding this to https://github.com/gulpjs/gulp/issues/651

**Comment by digitalmaster** [comment]
Tried their delay option.. doesn't work. 

Thanks.
