### ISSUE TITLE
No output generated using latest version

### ISSUE THREAD

**Issue by crissdev** [plus3network/gulp-less#159]
I'm using latest release of `gulp-less` to compile some `less` files and `gulp-concat` to combine them into a single bundle. The problem is that using `gulp-less@1.3.9` works as expected, but not with the latest release.
Here's how the gulp task is set up:

```js
gulp.task("styles", function() {
  return gulp.src(["styles/*.less", "app/**/*.less"], {cwd: "src"})
    .pipe(plugins.plumber(onTaskError))
    .pipe(plugins.sourceMaps.init())
    .pipe(plugins.concat("styles.less"))
    .pipe(plugins.less())
    .pipe(plugins.if(IS_RELEASE, plugins.minifyCss()))
    .pipe(plugins.sourceMaps.write())
    .pipe(gulp.dest("./dist/styles"));
});
```

The results are the following:
- `gulp-less@1.3.9` emits the expected output, no errors
- `gulp-less@3.0.2` doesn't emit any output, except the sourcemap. An error is also generated: "Potentially unhandled rejection [2] Error: ENOENT, open '~project/src/styles/styles.less'"

Is the usage between versions so different that I must do something else? Thanks.

**Comment by contra** [comment]
Can you isolate this to only the gulp-less module and publish a git repo that reproduces the issue?

**Comment by crissdev** [comment]
@contra Thanks. It seems the things go bad when source maps are enabled. https://github.com/crissdev/gl159

**Comment by stevelacy** [comment]
@crissdev can you pull from github/master to try the latest sourcemap fix?

**Comment by crissdev** [comment]
@stevelacy I've updated the repository to use the `master` branch but I receive the same error.
> Potentially unhandled rejection [2] Error: ENOENT, open '~/projects/gl159/src/styles/bundle.less'

I tried removing `gulp-concat` and it generated the `css` and the `map` file. But I really need the concatenation as well.

**Comment by stevelacy** [comment]
The concat must not be before the less build, this applies for any preprocessor.

**Comment by crissdev** [comment]
Thanks @stevelacy
