### ISSUE TITLE
Removes "display: -webkit-box;" ?

### ISSUE THREAD

**Issue by piarson** [plus3network/gulp-less#163]
After successfully parsing LESS file string "display: -webkit-box;" is not included into final CSS.

display : ~"-webkit-box;";
or
display e("-webkit-box");

are ignored also.

**Comment by stevelacy** [comment]
Please add:

`gulp-less` version
`less` version

Please confirm what the output is using the less CLI.

**Comment by piarson** [comment]
"name": "gulp",
  "version": "3.8.11",

  "name": "gulp-less",
  "version": "1.3.9",

  "name": "less",
  "version": "1.7.5",

BTW, found a hotfix 
display: replace(~"-webkit-something", 'something', 'box!important');
* must be used with !important, otherwise string will not be included in final css.

**Comment by contra** [comment]
Open an issue on less or whatever plugins you are using, all this library does is wrap less
