### ISSUE TITLE
Using a plugin such as autoprefix or less-plugin-clean-css will break the sourcemap generation

### ISSUE THREAD

**Issue by capaj** [plus3network/gulp-less#169]
With this task
```javascript
gulp.task('less', function () {
  return gulp.src('./my.less')
    .pipe(sourcemaps.init())
    .pipe(less({
      plugins: [autoprefix]
    }))
    .pipe(sourcemaps.write('.'))
    .pipe(gulp.dest(bundleDir));
});
```

there is an error thrown:
```
[10:47:38] Using gulpfile C:\projects\cdm-fe\gulpfile.js
[10:47:38] Starting 'less'...
Potentially unhandled rejection [2] Error: ENOENT: no such file or directory, open 'C:\projects\cdm-fe\<input css 1>'
```

using a less-plugin-clean-css will throw:
```
[10:49:23] Using gulpfile C:\projects\cdm-fe\gulpfile.js
[10:49:23] Starting 'less'...
Potentially unhandled rejection [2] Error: ENOENT: no such file or directory, open 'C:\projects\cdm-fe\$stdin'
    at Error (native)
```

This is probably a bug for those plugins right? Feel free to close this issue if this is the case, I will open bug for them in their repos and reference this one there.

**Comment by stevelacy** [comment]
That is an error on those plugins, from what this (un documented) issue shows, others have found issues as well: https://github.com/less/less-plugin-clean-css/issues/7

There also is this: https://github.com/less/less-plugin-clean-css/issues/6

I do not know what `autoprefix` is unless it is `gulp-autoprefixer`
