### ISSUE TITLE
Gulp process parameter for PostCSS plugin

### ISSUE THREAD

**Issue by p-ivannikov** [plus3network/gulp-less#173]
When i'm trying to add param for lost-grid ```@lost gutter 10px``` in less file i've got error message when gulp-less processed it. Can you say me how i can send parameters in lost-grid?

Lost-grid repo: https://github.com/corysimmons/lost
My opened issue for this ticket: https://github.com/corysimmons/lost/issues/149

**Comment by stevelacy** [comment]
`gulp-less` sends all files through to the less compiler. https://github.com/less/less.js/
