### ISSUE TITLE
When using Bootstrap, receive error "variable @alert-padding is undefined in file alerts.less line no. 10"

### ISSUE THREAD

**Issue by Hypermedia** [plus3network/gulp-less#175]
However, Bootstrap defines @alert-padding in variables.less line no. 623.

Is this a bug, or am I declaring something in the wrong order. 
I've tried declaring 'less/mixins' using the paths option for @import declarations, as well as *not* doing that as well. :)

**Comment by stevelacy** [comment]
This error is not related to this project, it is a [less](http://lesscss.org/) import error.

These answers should help: http://stackoverflow.com/questions/21994582/using-gulp-to-compile-bootstrap-less-files-into-main-bootstrap-css

Use the `@import` directive in your app.less file to import the root bootstrap file containing the variables.
