### ISSUE TITLE
Error: Unrecognised input

### ISSUE THREAD

**Issue by lmwa** [plus3network/gulp-less#177]
Dear Developer,

ill try to write this part:

figure {
   display: table;
    img {
        display: block;
        width: 100%;
    }
    figcaption {
        display: table-caption;
        caption-side: bottom;
    }​
}

and get this error message:

[11:04:07] { [Error: Unrecognised input in file RENAMED__FILE.less line no. 256]
  type: 'Parse',
  message: 'Unrecognised input in file RENAMED__FILE.less line no. 256',
  filename: 'RENAMED__FILE.less',
  index: 5576,
  line: 256,
  callLine: NaN,
  callExtract: undefined,
  column: 5,
  extract: [ '        caption-side: bottom;', '    }​', '}' ],
  lineNumber: 256,
  fileName: 'RENAMED__FILE.less',
  name: 'Error',
  stack: undefined,
  showStack: false,
  showProperties: true,
  plugin: 'gulp-less',
  __safety: { toString: [Function] } }

Best,
julian

Source:
http://www.w3schools.com/cssref/pr_tab_caption-side.asp
http://www.w3schools.com/cssref/pr_class_display.asp

**Comment by stevelacy** [comment]
The issue is not related to this plugin. Open it on the `less` repo
