### ISSUE TITLE
Using less@1.3

### ISSUE THREAD

**Issue by gandhiShepard** [plus3network/gulp-less#183]
Is it possible for me to use Gulp Less but run less@1.3? I'm trying to support a new project that can only be built with Less@1.3? If so, how do I make this config with this gulp plugin? Thanks!

**Comment by timtroup** [comment]
+1 I need to compile bootstrap 1.2.0 and this can only be built with less 1.3.3 AFAIK

PS: your contact address dev@plus3network.com just bounces

**Comment by cappslock** [comment]
I have this exact issue today. To the plugin author, I'd suggest removing less as a dependency entirely and allowing plugin users to supply their own `less` module.

I.e. as a user I would want to be able to do something like:
```
var less = require('gulp-less')(require('less')); // provide my own less version with a compatible API
```

Instead of:
```
var less = require('gulp-less'); // stuck with whatever version the plugin decides
```

**Comment by contra** [comment]
Really this is an accord issue - all this library does is wrap accord. AFAIK accord has something for overriding versions, check their README for that info and report back if you have any trouble

**Comment by tbranyen** [comment]
@contra not quite, this project has an explicit, locked dependency on [less@2.5.1](https://github.com/plus3network/gulp-less/blob/master/package.json#L24)

I'm still investigating a clean way to support legacy less versions

**Comment by tbranyen** [comment]
If you try:

```js
var accord = require('accord')
accord.load('less', path.join(__dirname, 'node_modules/less'));
```

This will result in:

>      throw new Error(name + " version " + version + " is not currently suppor
            ^
Error: less version 1.3.3 is not currently supported

**Comment by tbranyen** [comment]
I've created a fork of this project that correctly supports 1.3.3 (but had to remove source maps).  You can find it here: https://github.com/tbranyen/gulp-less-legacy

```
npm install gulp-less-legacy
```

**Comment by contra** [comment]
This seems like an issue you should open on the accord repo, possibly even send a PR to them to add support for older versions of less

**Comment by Rob-ot** [comment]
Good news! NPM fixed this situation we're in with Peer Dependencies.

https://nodejs.org/en/blog/npm/peer-dependencies/

**Comment by zaibigits099** [comment]
You can run into this issue when you've installed `gulp-less` but not also `less`

`npm install --save less`

**Comment by wt812haaply** [comment]
npm install gulp-less@3.0.0  试试
