### ISSUE TITLE
3.0.4 breaks dynamic imports

### ISSUE THREAD

**Issue by idefy** [plus3network/gulp-less#202]
May be it is due to the new version of less used, I haven't push very far my researches, but I know it fails with gulp-less 3.0.4 when it works well until 3.0.3.

For instance I have the following task that does this :
```javascript
 var tasks = themes.map(function(theme) {
	        var t = theme.slice(0, -5);
	        return gulp.src(config.less)
	            .pipe($.plumber())
	            .pipe($.less({
	            'modifyVars': {
	                    'theme': t
	                }
	            }))
	            .pipe($.rename('style-' + t + '.css'))
	            .pipe(gulp.dest(config.temp));
	    });
```

my less imports themes as such:
```less
@import "theme/@{theme}";

@import "some/other/less";
```

With 3.0.3 and before it works as expected. With 3.0.4 I get the error:
```node
[13:00:01] Plumber found unhandled error:
 Error in plugin 'gulp-less'
Message:
    variable @theme is undefined in file D:\Git\samfm-v2\Frontend\WebCore\src\st
yles\style.less line no. 6
Details:
    type: Name
    filename: D:\Git\samfm-v2\Frontend\WebCore\src\styles\style.less
    index: 161
    line: 6
    callLine: NaN
    callExtract: undefined
    column: 8
    extract:@import "theme/@{theme}";
    lineNumber: 6
    fileName: D:\Git\samfm-v2\Frontend\WebCore\src\styles\style.less
```

**Comment by craigjennings11** [comment]
I'm also having a similar issue. It doesn't seem to be less's fault since
https://github.com/plus3network/gulp-less/commit/7004142380a709abe8e4d1cac6935bf8dcc1ba41#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L24 would download the latest version of less, `v2.5.3`.

**Comment by craigjennings11** [comment]
Can you check and see if the change in #203 fixes this issue? It fixed it for my case.
