### ISSUE TITLE
Less files with multiline block comments break source maps when using minify-css

### ISSUE THREAD

**Issue by rros** [plus3network/gulp-less#204]
The combination of gulp-less, gulp-sourcemaps and gulp-minify-css has an issue if one of the sources files (less or css) contains multiline block comments.

gulp-sourcemaps issues a warning: ` No source content for "1.css". Loading from file.` The generated sourcemap is also invalid. 

Expected source map:
```json
{"version":3,"sources":["1.less"],"names":[],"mappings":"AAEA,KACI,WAAA","file":"1.min.css","sourcesContent":["/*\nThis is a multiline block comment\n*/\n\nbody {\n    background: red;\n}\n"],"sourceRoot":"/source/"}
```

Actual source map:
```json
{"version":3,"sources":["1.css"],"names":[],"mappings":"AACA,KACE,WAAY","file":"1.min.css","sourcesContent":[null],"sourceRoot":"/source/"}
```

This issue should be reproducible with the following testcase: https://github.com/rros/gulp-less-block-comments-issue

I'm not sure this is the right place to report this issue, but I guess gulp-less is responsible for creating the source map and gulp-sourcemaps is just responsible for writing the generated source maps.

**Comment by contra** [comment]
Does using the less library (or CLI) directly also reproduce this issue?

**Comment by rros** [comment]
I tried the CLI version (installed via npm) and I think it does.

Test.less
```less
/*
This is a multiline block comment
*/
body {
        background: red;
}
```

`lessc --clean-css --source-map-less-inline --source-map=test.min.css.map --verbose test.less > test.min.css`

Output:
`{"version":3,"sources":["$stdin"],"names":[],"mappings":"AACA,KACE,WAAY","sourcesContent":[null]}`

Expected output:
`{"version":3,"sources":["test.less"],"names":[],"mappings":"AACA,KACQ,WAAA","sourcesContent":["/*\nThis is a multiline block comment\n*/\nbody {\n        background: red;\n}\n"]}`

Because I used the clean-css plugin, it could also a problem in clean-css.

**Comment by contra** [comment]
@rros If the CLI also reproduces the issue then it is a less bug and you should file it on their tracker so they can get it fixed https://github.com/less/less.js/issues

**Comment by rros** [comment]
I finally found the issue is with clean-css: https://github.com/jakubpawlowicz/clean-css/issues/593

Basically the comments processor of clean-css assumes the newlines in the input sourcemap (the one generated by less) will match the newlines of the OS it's running on. Clean-css will corrupt the sourcemap when it assumes the incorrect newlines.
