### ISSUE TITLE
gulp-less print out nothing error in case extend a non-existing mixin

### ISSUE THREAD

**Issue by cnweibo** [plus3network/gulp-less#206]
Hi, I have posted a thread in stackoverflow about gulp-less. I want to know how to deliver error information when an error happens during extend a non-existing mixing/class.
http://stackoverflow.com/questions/34107876/is-there-any-way-to-let-gulp-less-print-error-in-case-extend-a-non-existing-mixi

Can you have a look and give me clue. Following is copied from stackoverflow:

In my less build process, i use the gulp-less. In the build process, i use gulp-plumber to print out error information during that build. It works well for the less syntax error, reference to non-exist variables. Unfortunately, the gulp-less build task print out nothing in case we extend a non-existing mixin/class. Does anyone know about how to enable such kind of "error" or even warning during the build? Following is the gulpfile:
 gulp.task('less',function(){
    var pagelessentry = config.pagelessentry;
    log(pagelessentry);
   return gulp
       .src(pagelessentry)
       .pipe(plumber({
            errorhandler: errorhandler
       }))
       .pipe(debug({
            title: 'LESS'
       }))
       .pipe(sourcemaps.init())
       .pipe(less())
       .pipe(uncss({
            html: ['index.html', 'http://homestead.app'],
            ignore: [/header-down/,/header-up/]
        }))
       .pipe(sourcemaps.write(projectrootdir+'public/preparebuild/assets/css/',{includeContent: true}))
       .pipe(gulp.dest(projectrootdir+'public/preparebuild/assets/css/'));
});
Following is the "wrong" less code where i want gulp to print out some "error or warning" information:
 .footer{
    background-color: @primary-background;
    &:extend(.NONEXISTING all);
}
In above code, when we extend .NOEXISTING mixin, nothing printed out.
It is quite annoying thing.
Please help me out
Thanks~!

**Comment by contra** [comment]
Does this happen with the less command line as well?

**Comment by cnweibo** [comment]
@contra , for the lessc itself, it really dump out an warning when extending a non-existing class.
according to http://stackoverflow.com/questions/31751746/show-warnings-when-extend-is-missing-base-class/31759983#31759983 , someone tells gulp-less should implement a  dedicated support for such warnings (there was no "warnings-facility" in Less before).
As i know, grunt-contrib-less also can not print out these warning.
Can you give more information how can i let that happen in gulp-less?
This is really useful since no glue to know what happens when that happen.
Thanks!

**Comment by cnweibo** [comment]
@contra , i have run in the linux command line with lessc --lint, it really printed out the missed extended class as follows(.clearfix can not be found when extend it!):
```bash
vagrant@homestead:~/nodewrapper$ lessc --lint /home/vagrant/Code/kidsit/resources/assets/less/style.less 
extend ' .clearfix' has no matches
extend ' .clearfix' has no matches
extend ' .clearfix' has no matches
```

**Comment by contra** [comment]
This seems like an issue where less is not reporting errors back via the JS API. You should open an issue with less so they can add this in.

**Comment by cnweibo** [comment]
ok, i have opened an issue on less repo. Hope they can have a investigation. But currently, they have not admit, it is less itself's issue.

**Comment by cnweibo** [comment]
@contra , please see reply from less guys, it seems that the less compiler itself has exported the warnings to tooling. So, i think, if gulp-less accept some configuration parameter, this can work.
https://github.com/less/less.js/issues/2753#issuecomment-162291341
Please see the demo code they provide for information here.

**Comment by contra** [comment]
@cnweibo Do you want to send a PR to add this? We don't use the less module directly, we use accord which doesn't give us access to this stuff. It will probably need to be added to accord then we can add a warning event from this plugin

**Comment by cnweibo** [comment]
@contra , sorry, i do not know how to let this issue fix by accord.
Can you tell me what is the repo of accord, i can submit the issue to them to fix it. Or..can you kindly submit an issue to accord?

Thanks~!

**Comment by contra** [comment]
@cnweibo https://github.com/jenius/accord/issues/128
