### ISSUE TITLE
Imports still broken?

### ISSUE THREAD

**Issue by hackel** [plus3network/gulp-less#216]
I am using 3.0.5, but still experiencing the issue described in #202.  In my main less, I `@import bootstrap`, which `@imports variabes`, then I import another app.less file which uses one of those variables, but gulp gives me the "variable is undefined" error.  If I compile main.less with lessc directly (the same lessc binary installed by gulp-less!), it works flawlessly.  Not sure what's going on here.  If I `@import variables` in my app.less also, gulp-less doesn't complain.

Edit: Just realized that even though gulp-less gives me that error, it still works, and generates the exact same files whether I @include the variables in my app.less or not.

**Comment by contra** [comment]
@hackel Can you recreate your problem using less directly?

**Comment by hackel** [comment]
No, as I said above.

**Comment by stevelacy** [comment]
Control flow of files:

https://github.com/stevelacy/gulp-less-216

Note that there is only one less root file `normal.less`, not a glob array of all .less files.
For farther debugging please create a repo to reproduce the issue.

**Comment by hackel** [comment]
Hmm, I'm not using a glob of all less files, but I am passing an array of a few different specific less files.  I will see if isolating it makes a difference.  Thanks.

**Comment by stevelacy** [comment]
@hackel updates?

**Comment by hackel** [comment]
@stevelacy Sorry, I can no longer reproduce this issue, so hopefully it was just some configuration oddity.

**Comment by roopkt** [comment]
Hi 
I am using   "gulp-less": "^3.5.0" and I am not able to import variables getting below error:
```
[15:33:02] Plumber found unhandled error:
 Error in plugin "gulp-less"
Message:
    variable @import is undefined in file...\Content\assets\less\myfiles.less line no. 3
Details:
    type: Name
    filename: ...\Content\assets\less\myfiles.less
    index: 53
    line: 3
    callLine: NaN
    callExtract: undefined
    column: 0    extract: /*COLORS*/,@import "variables.less"; ,
    lineNumber: 3
    fileName: ..\Content\assets\less\myfile.less
```

variable.less file is below 
```
@dark-gray: #000;
@light-gray: #a4aeb3;
@teal: #043a4e;
@orange: #d74c15;
@hover-orange: #b44012;
```

myfile.less is below

```
/*COLORS*/
@import "variables.less"; 

@primaryTextColor: @dark-gray;
@secondaryTextColor: @light-gray;
@primaryAccentColor: @teal;
@secondaryAccentColor: @orange;
```
