### ISSUE TITLE
accord is breaking down some less.js plugins

### ISSUE THREAD

**Issue by Justineo** [plus3network/gulp-less#222]
See https://github.com/jenius/accord/issues/165.

**Comment by contra** [comment]
@Justineo Why post here if the issue is in accord?

**Comment by Justineo** [comment]
Just mention this because if `accord` doesn't fix this, `gulp-less` may have to make some change if it want plugins work correctly.

But now knowing `accord` will fix this, it shouldn't be an issue for `gulp-less` anymore.
