### ISSUE TITLE
Plugin crashes 

### ISSUE THREAD

**Issue by achugaev93** [plus3network/gulp-less#223]
Error in file:
..../node_modules/gulp-less/index.js on line 68

...
    }).done(undefined, cb);
...

It crashes build process, because `.done` is not defined. Maybe, it is invalid usage of promises.

**Comment by achugaev93** [comment]
Change `.done` to `.then` an it will work fine.

**Comment by tripstar22** [comment]
I also had this issue and @achugaev93's solution worked for me. Definitely something I did not expect to encounter when I installed this plugin.

**Comment by contra** [comment]
@tripstar22 What version of less is installed?

**Comment by tripstar22** [comment]
@contra I have version 2.7.1 which is the latest version according to https://www.npmjs.com/package/less
