### ISSUE TITLE
gulp-less minor dependency on less introduce : Source map bug introduced in less 2.7.0

### ISSUE THREAD

**Issue by mlardy** [plus3network/gulp-less#237]
Hi

I'm stucked with a less bug : 
**_ Error in plugin 'gulp-less'
Message:
    Invalid mapping: {"generated":{"line":190,"column":2},"source":".../bootstrap/less/print.less","original":{"line":1,"column":null},"name":null} in file undefined line no. undefined
Details:
    lineNumber: undefined
    fileName: undefined_**

I think that you should not reference minor version changes in your package.json for less dependency.

If there are some bugs in dependencies like this one https://github.com/less/less.js/issues/2896 we can't use a previous minor version of gulp-less with a previous less minor version.

You should probably release a gulp-less 3.1.x to point to a less ~2.6.x and upgrade minor of gulp-less when a less minor is released.

**Comment by leighgordy** [comment]
I'm having the same issue. Your plugin is pulling the latest less 2.7.0 which is currently broken. Changing your project so that it references 2.6.1 will bypass the issue.

**Comment by leighgordy** [comment]
Commenting out reference to gulp-source maps in the gulp script is the quickest way to bypass the 2.7.0 issue. e.g. pipe(sourcemaps.init()) pipe(sourcemaps.write('./')).

**Comment by felixfbecker** [comment]
The best way would be if gulp-less had the option to pass a custom reference to the less reference, like gulp-typescript does. That way we could all easily revert to less@2.6
Example:
```js
const gulpLess = require('gulp-less')
const less = require('less')

gulp.src('app.less')
  .pipe(gulpLess({less, paths: [__dirname + 'node_modules']}))
  .pipe(gulp.dest('build'))
```

**Comment by oBusk** [comment]
We would really like to be able to pass less as an option to have better control over which version to use. 

```javascript
const gulpLess = require('gulp-less');
const less = require('less');

gulp.src('app.less')
    .pipe(gulpLess({
        less: less
    });
    .pipe(gulp.dest('build'));
```

Similiar to how [gulp-typescript](https://www.npmjs.com/package/gulp-typescript#typescript-version) does it. 

However i guess it would be more correct and work even smoother if less was added as a peer dependency?

----

For anyone having this problem now do a `npm install`, [`npm shrinkwrap --dev`](https://docs.npmjs.com/cli/shrinkwrap) and then modify the shrinkwrap version of "less" to be `2.6.1`.

```javascript
...
"less": {
          "version": "2.6.1",
          "from": "less@>=2.6.1 <2.7.0",
          "resolved": "https://registry.npmjs.org/less/-/less-2.6.1.tgz",
          "dependencies": {
...
```

**Comment by davetheflashguy** [comment]
Ran into this today, I too ended up doing what @leighgordy suggested.

**Comment by lucknerjb** [comment]
^ Ditto! Thanks @oBusk

**Comment by oBusk** [comment]
This should have been [fixed with a `2.7.1` version of `less`](https://github.com/less/less.js/issues/2896#issuecomment-217983154). Doing an npm install/update should fix this problem. `gulp-less` would still benefit greatly from an ability to use a specific version of less.

**Comment by johnkors** [comment]
Related?

```
[15:42:00][Step 6/6] [15:42:00] Starting 'boostrapLess'...
[15:42:00][Step 6/6] [15:42:00] Starting 'less'...
[15:42:01][Step 6/6] [15:42:01] Invalid mapping: {"generated":{"line":1289,"column":2},"source":"Content/Styles/Libs/Bootstrap-3.3.6/type.less","original":{"line":1,"column":null},"name":null} in file undefined line no. undefined
[15:42:01][Step 6/6] [15:42:01] Finished 'boostrapLess' after 1.56 s
[15:42:02][Step 6/6] [15:42:02] Finished 'less' after 2.04 s
```

**Comment by davetheflashguy** [comment]
Yup @johnkors , I had the same issues yesterday with boostrap
