### ISSUE TITLE
Issue referencing vars and mixins from imports

### ISSUE THREAD

**Issue by expjson** [plus3network/gulp-less#241]
I'm seeing errors like the following: `Potentially unhandled rejection [2] variable @type300 is undefined in file /src/git/uitoolkit/web/src/main/webapp/static/documentation/styles/docs-codeblocks.less` when I attempt to compile a LESS file if the mixins and vars are imported into a parent file instead of the local file. 

Here is the task: 
```js

gulp.task('less:docs', ['minify:core:css'], function () {
    return gulp.src('./web/src/main/webapp/static/documentation/styles/' +  '**/*.less')
        .pipe(plugins.less())
        .pipe(gulp.dest(assetPaths.docs.styles.dest));
});
```

some of the imports are in a directory a couple directories up. for example `docs.less`:
```less
@import "../../core/styles/mixins";
@import "../../core/styles/mixins-type";
@import "my-file";
```

Inside `my-file.less` I'm referencing a variable from `mixins` which is imported into `docs.less`.

We need to use the file glob as there are many single root LESS files  but the issue is the same. Also, I'm using `3.1.0` of gulp-less. 

Any ideas?

**Comment by dblboy** [comment]
+, i'm having the same issue, when importing variable.less into parent file, i can't use them in other local files

**Comment by stevelacy** [comment]
Change your source to ONLY include the root (parent) file instead of a glob, OR import the mixin and variable files into each individual file.
Each file is a separate file in the stream. If a child file does not import the mixins then the variables are undefined.
