### ISSUE TITLE
$.less is not a function

### ISSUE THREAD

**Issue by tihumihu** [plus3network/gulp-less#244]
import gulp from 'gulp';
import gulpLoadPlugins from 'gulp-load-plugins';
import browserSync from 'browser-sync';
import del from 'del';
import {stream as wiredep} from 'wiredep';

const $ = gulpLoadPlugins();
const reload = browserSync.reload;

gulp.task('styles', () => {
  return gulp.src('app/styles/*.less')
    .pipe($.less())
    .pipe($.sourcemaps.init())
    .pipe($.autoprefixer({
      browsers: ['last 2 versions', 'last 1 Chrome versions','last 2 Explorer versions'],
      cascade: true, //是否美化属性值 默认：true 像这样：
      remove:false //是否去掉不必要的前缀 默认：true
    }))
    .pipe($.minifyCss())
    .pipe(gulp.dest('.tmp/styles'))
    .pipe(reload({stream: true}));
});

[17:26:08] Requiring external module babel-register
[17:26:14] Using gulpfile ~/wangshang/gulpfile.babel.js
[17:26:15] Starting 'styles'...
[17:26:15] 'styles' errored after 8.62 ms
[17:26:15] TypeError: $.less is not a function
    at Gulp.<anonymous> (gulpfile.babel.js:13:13)

**Comment by contra** [comment]
Doesn't have anything to do with this plugin - open it on gulp-load-plugins
