### ISSUE TITLE
Possible to snap a new release?

### ISSUE THREAD

**Issue by robertdbailey** [plus3network/gulp-less#256]
@stevelacy and plus3network team, would it be possible to push a new release of gulp-less to get the accord library version change into an official release?  Thanks very much for all the help with your libraries!

**Comment by stevelacy** [comment]
@simianhacker Publish please? Or we could transfer the project.

**Comment by robertdbailey** [comment]
@simianhacker, let me know if there is anything I can do to help this along.  Thanks, and thanks @stevelacy !

**Comment by stevelacy** [comment]
Just realized that I have publish rights - published to 3.2.0
