### ISSUE TITLE
wish: update Changelog

### ISSUE THREAD

**Issue by markstos** [plus3network/gulp-less#257]
The Changelog only documents changes through 3.0.1, while the current version is 3.2.0:

https://github.com/plus3network/gulp-less/blob/master/Changelog.md

It would be helpful if the changelog were current.

**Comment by stevelacy** [comment]
I use git tags as releases to indicate the changelog, I did merge the changelog update PR, thanks!

https://github.com/plus3network/gulp-less/releases
