### ISSUE TITLE
webstorm cannot save files

### ISSUE THREAD

**Issue by 953133667** [plus3network/gulp-less#262]
# Webstorm idea cannot save files.
I created a file, name is  filename.less. (use webstorm)
### Run the gulp task:
```
gulp.task('css', function() {
    return gulp.src('src/less/page/**/*.less')
        .pipe(less())
        .pipe(minifycss())
        .pipe(rename({ suffix: '.min' }))
        .pipe(gulp.dest('dest/css/page'));
});
```
System auto created a file, name is filename.less___jb_tmp___.
Webstorm pop-up window 
for example：
![qq 20161130142635](https://cloud.githubusercontent.com/assets/9947354/20742077/11894fcc-b709-11e6-91ba-f27c7413e335.png)
Can i not create the filename.less___jb_tmp___?
Please help me. Thx !

**Comment by contra** [comment]
This doesn't have anything to do with gulp or gulp-less, this is some issue with your webstorm setup or filesystem permissions.
