### ISSUE TITLE
TypeError: less is not a function

### ISSUE THREAD

**Issue by webdesignmx05** [plus3network/gulp-less#265]
I previously posted this issue but it was deleted perhaps something was ...my variables are uniquely defined for gulp and less separated with a comma. Why am I receiving this error? Less is defined and installed in the package.json "gulp-less": "^3.3.0". All other gulp plugins I use work as expected. Note: this code similar to a video tutorial on egghead.io for precompiling-your-less-files-with-gulp so it should work.
 
Upon running this task, i receive the following error. 

var gulp = require('gulp'), 
less = require('gulp-less');

gulp.task('compile-less', function() {
	 return gulp.src('source/less/main.less')
     .pipe(less())
     .pipe(gulp.dest('build/css'));
});

$ gulp compile-less
sass-lang 1.0.0, development build
[11:57:46] Using gulpfile C:\wamp\www\sass-lang\gulpfile.js
[11:57:46] Starting 'compile-less'...
[11:57:46] 'compile-less' errored after 9.33 ms
[11:57:46] TypeError: less is not a function
    at Gulp.<anonymous> (C:\wamp\www\sass-lang\gulpfile.js:155:12)
    at module.exports (C:\wamp\www\sass-lang\node_modules\orchestrator\lib\runTask.js:34:7)
    at Gulp.Orchestrator._runTask (C:\wamp\www\sass-lang\node_modules\orchestrator\index.js:273:3)
    at Gulp.Orchestrator._runStep (C:\wamp\www\sass-lang\node_modules\orchestrator\index.js:214:10)
    at Gulp.Orchestrator.start (C:\wamp\www\sass-lang\node_modules\orchestrator\index.js:134:8)
    at C:\Users\rramey\AppData\Roaming\npm\node_modules\gulp-cli\lib\versioned\^3.7.0\index.js:46:20
    at nextTickCallbackWith0Args (node.js:420:9)
    at process._tickCallback (node.js:349:13)
    at Function.Module.runMain (module.js:443:11)
    at startup (node.js:139:18)

**Comment by stevelacy** [comment]
Do not open the same issue, it was not deleted: https://github.com/plus3network/gulp-less/issues/264

I will post screenshots of what I wrote there so there is proof that I am not editing your comments:

Look again at the code you Just posted. Add a `var` before the `less`.

Screenshots for proof so you can not blame me for editing
![selection_00120171110 07 50](https://cloud.githubusercontent.com/assets/5648999/21858316/dc56e8f2-d7e5-11e6-8bf9-3382daa7e775.png)
 Your comment:

![selection_00120171110 04 59](https://cloud.githubusercontent.com/assets/5648999/21858205/7b4484ac-d7e5-11e6-8526-441b5d61c926.png)

Change your less require to this:

![selection_00120171110 07 06](https://cloud.githubusercontent.com/assets/5648999/21858274/b9da3f7c-d7e5-11e6-96eb-1a78dee4ef57.png)

Copy and paste this:

```js
var less = require('gulp-less');
```

**Comment by webdesignmx05** [comment]
sorry that is incorrect, less is already present as less = require('gulp-less')...there are multiple variables present for the other plugins but i have shortened it to these 2 for simplicity.

**Comment by webdesignmx05** [comment]
FWIW...i tried less on a separate line with the preceding var and still get the same error.
var less = require('gulp-less')

**Comment by stevelacy** [comment]
Please post your full gulpfile

**Comment by webdesignmx05** [comment]
Sure. Please see attachment.
[gulpfile.zip](https://github.com/plus3network/gulp-less/files/699724/gulpfile.zip)

**Comment by stevelacy** [comment]
I just ran it without any issues.

This code does work:

```js
var gulp = require('gulp');
var less = require('gulp-less');

gulp.task('compile-less', function() {
   return gulp.src('main.less')
     .pipe(less())
     .pipe(gulp.dest('build'));
});
```

**Comment by webdesignmx05** [comment]
I certainly believe you that it works because I've seen plenty of resources all across the web demonstrating gulp-less working for but somehow it throws that same error message in my environment and it is the only plugin I've across that I'm experiencing this issue...not just one one computer but several others with npm and gulp installed. Granted, these are windows 7 with npm v4.4.5 for one and v3.9.5 - both with gulp 3.9.1 local/ 1.2.2 CLI. Additionally, a node developer I work nearby is also experiencing the same issue on his computer with this plugin. 

I have to ask...does this plugin only work with the latest or a specific version of npm or gulp? I'd expect it to be backwards compatible with older versions so I don't want to update them unless absolutely necessary. Attempts at trying to delete or uninstall gulp-less and re-install to install a lower version as one threat on a forum suggested did not work either. Even, installing it on another machine with with the exact code verbatim above (only those 2 plugins) also gave the same error message so I am out of ideas.

**Comment by stevelacy** [comment]
Ah, windows may be a factor.
Ok, can you fire up a node repl in the project folder and enter each to see what their output is?
```js
> var less = require('gulp-less'); 
> less
> less()
```

Then these:

```js
> var accord = require('accord');
> var lessa = accord.load('less');
> var lessc = require('less');
> lessa
> lessa.render()
> lessc
> lessc.render()
```

gulp is backwards compatible with this plugin, and npm > 3 should not give any issues. The tests are passing on node 0.10-6 running on linux.
I can see if I can get onto a windows machine as well.

**Comment by webdesignmx05** [comment]
Here is what i see when I enter those using MINGW64 - see attachment.
[gulp-less-tests.txt](https://github.com/plus3network/gulp-less/files/700704/gulp-less-tests.txt)

**Comment by stevelacy** [comment]
Odd, everything looks fine.

Can you run a gulpfile with just this and a simple less file?

```js
var gulp = require('gulp');
var less = require('gulp-less');

gulp.task('compile-less', function() {
  try {
    gulp.src('main.less')
       .pipe(less())
       .on('error', console.log)
       .pipe(gulp.dest('build'))
       .on('end', console.log);
  }
  catch (e) { 
    console.log(e);
  }
});
```

I am wondering if it is the less compiler throwning an error on a line of `.less` code.

**Comment by webdesignmx05** [comment]
It gives this message:

$ gulp compile-less
sass-lang 1.0.0, development build
[11:17:34] Using gulpfile C:\wamp\www\sass-lang\gulpfile.js
[11:17:34] Starting 'compile-less'...
[TypeError: less is not a function]
[11:17:34] Finished 'compile-less' after 11 ms

I have also attached the main.less file that I'm using which I observed someone compile using gulp-less. I even tried this below and saw the same error.

@base: #f938ab;

.hello {
	background: @base;
}

[main.zip](https://github.com/plus3network/gulp-less/files/702221/main.zip)

**Comment by webdesignmx05** [comment]
Wait...i just got it to work in an new directory (on the same machine - win7)...with no other plugins but gulp and gulp-less.
Not sure if maybe another plugin is causing some interference. Are there any known conflicts?

**Comment by stevelacy** [comment]
None have been reported that cause less to error in the same file, only when piped into another plugin.
Can you run `compile-less` in the folder which causes the issue and comment out the sass and css task?
And the output of: `npm run ls less` in both the working folder and the issue folder.

**Comment by webdesignmx05** [comment]
I have found the issue...it seems I was using the word less as a variable and gulp-less didn't like it.
I like to define my paths outside of the gulp task and then just reference the paths by the variable. You can't use the word "less" as the variable name...you must use something else like 'lesscss' instead as it will throw an error but it didn't make sense to me since I am used to method calls having parenthesis like less(). However, the gulp-sass plugin (and perhaps every other plugin) does the same thing but I already had 'scss' defined for my sass variables so I didn't see this issue earlier. The error makes sense now. Initially when i created the new folder with new gulp.js file even though I had the compile-less task with the absolute paths, the variables at the top were in there unused and gulp still gave the same error. I would imagine others probably make the same error. Thank you so much for your help. 

        var source = 'source/',
	dest = 'build/',
	lesscss = {
		in: source + 'less/main.less',
		out: dest + 'css/',
	},

gulp.task('compile-less', function() {
	 
	  try {
    	gulp.src(lesscss.in)
       .pipe(less())
       .on('error', console.log)
       .pipe(gulp.dest(lesscss.out))
       .on('end', console.log);
	  }
	  catch (e) { 
	    console.log(e);
	  }
});

**Comment by webdesignmx05** [comment]
Exactly...that's exactly what i did. Thank you sir!

**Comment by stevelacy** [comment]
Ah, makes sense, glad to help!
