### ISSUE TITLE
less-plugin-autoprefix plugin doesn't work

### ISSUE THREAD

**Issue by JsonMa** [plus3network/gulp-less#268]
`
var LessAutoprefix = require('less-plugin-autoprefix'),
    autoprefix = new LessAutoprefix({
        browsers: ["last 2 versions", "iOS >= 4", "ie > 8", "firefox >= 15"],
        cascade: true
    });
gulp.task('compile-less', function () {
    gulp.src('./public/less/**/*.less')
        .pipe(sourcemaps.init())
        .pipe(plumber({errorHandler: notify.onError('Error: <%= error.message %>')}))
        .pipe(changedInPlace()) // 用于编译改动的文件
        .pipe(less({
            plugins: [autoprefix]
        }))
        .pipe(sourcemaps.write(sourceMapPath))
        .pipe(debug({title: '编译了文件:'}))
        .pipe(gulp.dest('./public/css'));
});`

**Comment by stevelacy** [comment]
This is gulp-less, not less-plugin-autoprefix
