### ISSUE TITLE
compile with earlier less version

### ISSUE THREAD

**Issue by smartfaceweb** [plus3network/gulp-less#42]
Is there anyway to make gulp-less use an earlier version of less rather than the latest. I have a legacy bootstrap 2 app in which the less can only be compiled with less@1.3.

**Comment by schnittstabil** [comment]
You may want to try `npm shrinkwrap`, manually modify `npm-shrinkwrap.json` and reinstall your deps.

**Comment by contra** [comment]
1.x -> 2.x has too many breaking changes to support this. If you want to use a 1.x version of less then use a 1.x version of gulp-less
