### ISSUE TITLE
How to use modifyVars

### ISSUE THREAD

**Issue by blaugueux** [plus3network/gulp-less#50]
Hi everyone,

I really don't understand how to use modifyVars with ```gulp-less```. I can't find any docs about this.

Here is my code : 
```
// ...
.pipe(less({modifyVars: {myVar: 1}});
// ...
```
I ran this error : 
```Error in plugin 'gulp-less': variable @myVar is undefined in file...```

Thanks for your help

**Comment by contra** [comment]
Duplicate of #67
