### ISSUE TITLE
Impossible to use the globalVars / modifyVars option for rendering

### ISSUE THREAD

**Issue by ziarrek** [plus3network/gulp-less#67]
Currently, it is impossible to pass the `globalVars` or `modifyVars` options to gulp-less.
From what I have found, LESS passes the `options` argument from `less.render` to the `less.Parser` constructor (https://github.com/less/less.js/blob/c290c4/lib/less/index.js#L17) and the `globalVars`/`modifyVars` options are taken from the `parser.parse` call (https://github.com/less/less.js/blob/84407/lib/less/parser.js#L358-L359).
I am not sure if it's something gulp-less should adapt to, or if I should report it as an issue of less. Any comment would be appreciated.

**Comment by contra** [comment]
Can you test this on 3.0.0?
