### ISSUE TITLE
Regression introduced in v1.3.3?

### ISSUE THREAD

**Issue by lukehorvat** [plus3network/gulp-less#83]
I am experiencing a problem with upgrading from version 1.3.2 of gulp-less.

I've set up a small repository [here](https://github.com/lukehorvat/gulp-less-debug) to try and capture the problem in a reproducible form. Basically, I have a `watch` task that starts a `build` task every time my LESS files change. Standard.

For version 1.3.2, any syntax errors in my LESS files cause the `build` task to print an error message to the console, which is what I want. But for version 1.3.3 and up, my `build` task does not even seem to run after a LESS syntax error is encountered. :(

From what I can tell, it is stemming from [this commit](https://github.com/plus3network/gulp-less/commit/11af5a65df26d8a6cd6ba366a32ca2fe8b742474).

**Comment by contra** [comment]
This should be fixed in 2.0.3
