### ISSUE TITLE
sourceMap option is overridden

### ISSUE THREAD

**Issue by xpavelf** [plus3network/gulp-less#92]
according to less documentation 
"gulp-less: Please note that this plugin only generates inline sourcemaps (with sourceMap: true) - specifying a sourceMapFilename option will do nothing."

It is possible to generate inline source maps without gulp-sourcemaps just by setting sourceMap options to true. However the option is overridden in index.js so it never gets to less compiler.

https://github.com/plus3network/gulp-less/blob/master/index.js#L36

therefore I think that this line should be removed.

**Comment by contra** [comment]
You should be using gulp-sourcemaps - plugins do not handle their own sourcemaps, they all run through gulp-sourcemaps
